esp_toml_version = 1.0

# Base URL of the file server where the images are available
firmware_images_url = "https://motivo-hub.github.io/motivo-hub/fw/"

supported_apps = ["Normal-Update_C-0_2_1"]

[Normal-Update_C-0_2_1]
chipsets = ["auto-detect"]
image.auto-detect = "fw_10000_C-0.2.1.bin"
offset = "0x10000"
description = "PGI Filter Analyzer - Normal Update F/W ver. C-0.2.1"
readme.text = "https://motivo-hub.github.io/motivo-hub/fw/ReleaseNotes.C-0.2.1.md"

config_readme_url = "https://motivo-hub.github.io/motivo-hub/fw/ReleaseNotes.C-0.2.1.md"
