esp_toml_version = 1.0

# Base URL of the file server where the images are available
firmware_images_url = "https://motivo-hub.github.io/motivo-hub/fw/"

supported_apps = ["Normal-Update_A-0_3_0"]

[Normal-Update_A-0_3_0]
chipsets = ["auto-detect"]
image.auto-detect = "fw_10000_A-0.3.0.RC1.bin"
offset = "0x10000"
description = "PGI Filter Analyzer - Normal Update F/W ver. A-0.3.0 (User settings will be preserved)"
readme.text = "https://motivo-hub.github.io/motivo-hub/fw/ReleaseNotes.A-0.3.0.client.md"

config_readme_url = "https://motivo-hub.github.io/motivo-hub/fw/ReleaseNotes.A-0.3.0.client.md"
